"""Write an exact vector sparsity diagram using only standard Python and LaTeX."""
from pathlib import Path
import sys

assert sys.prefix != sys.base_prefix, "Use the draft's .venv/bin/python"
N = 120

def factors(n):
    primes, squarefree = [], True
    p = 2
    while p <= n:
        if n % p == 0:
            count = 0
            while n % p == 0:
                n //= p
                count += 1
            primes.append(p)
            squarefree &= count == 1
        p += 1
    return squarefree, primes[-1] if primes else 1

data = {i: factors(i) for i in range(1, N + 1)}
red = {(i, j) for i in data for j in data if i == 1 or i % j == 0}
sparse = {(i, j) for i in data for j in data
          if i == 1 or i == j or (i > 1 and data[i][0] and j == i // data[i][1])}
assert sparse <= red
assert len(red) == 721 and len(sparse) == 313
assert {j for i, j in sparse if i == 30} == {6, 30}
assert len(sparse) == 2 * N + sum(sf for sf, _ in data.values()) - 2

out = [r"% Generated by build_comparison.py; exact entries, no raster image.",
       r"\begingroup\setlength{\unitlength}{1pt}",
       r"\definecolor{cmpRow}{HTML}{C27627}",
       r"\definecolor{cmpDiag}{HTML}{838B91}",
       r"\definecolor{cmpParent}{HTML}{007F7A}",
       r"\definecolor{cmpExtra}{HTML}{779CC3}",
       r"\begin{picture}(468,264)"]

def label(x, y, value, size=9, align="c"):
    out.append(r"\put(%.3f,%.3f){\makebox(0,0)[%s]{\fontsize{%d}{%d}\selectfont %s}}"
               % (x, y, align, size, size + 2, value))

side, bottom = 194, 33
step = side / N
for left, entries, title in [(26, red, r"Redheffer, transposed: $R_{120}^T$"),
                              (270, sparse, r"Sparse parent matrix: $B_{120}$")]:
    label(left + side / 2, 255, title, 10)
    label(left + side / 2, 240, str(len(entries)) + " nonzero entries")
    for i, j in sorted(entries):
        color = "cmpRow" if i == 1 else "cmpDiag" if i == j else "cmpParent" if (i, j) in sparse else "cmpExtra"
        out.append(r"\put(%.3f,%.3f){\color{%s}\rule{%.3fpt}{%.3fpt}}"
                   % (left + (j - 1) * step + .05, bottom + (N - i) * step + .05,
                      color, step - .1, step - .1))
    for k in [1, 30, 60, 90, 120]:
        label(left + (k - .5) * step, bottom - 10, str(k), 8)
        label(left - 5, bottom + (N - k + .5) * step, str(k), 8, "r")
    label(left + side / 2, 7, r"column $j$")
    label(left - 3, 237, r"row $i$", 8, "r")
out.extend([r"\end{picture}", r"\endgroup"])
Path(__file__).with_name("redheffer-comparison.tex").write_text("\n".join(out) + "\n")
print("Wrote vector diagram: 721 Redheffer entries; 313 sparse entries.")
